### ISSUE TITLE
Add Community Bundle PRs to list of open lib PRs

### ISSUE THREAD

**Issue by kattni** [adafruit/adabot#134]
So we don't miss PRs to the Community Bundle.

**Comment by sommersoft** [comment]
With the changes from #130, I assume this applies only to circuitpython.org/contributing?

Or do you want to add "the full compliment" to the daily report?

**Comment by kattni** [comment]
We should include this in the list of merged PRs that #130 now expects in the daily report, and include it in the number of open PRs that will still be in the daily report as well. Let me know if this is unclear.
