### ISSUE TITLE
Library Report: Consider replacing core download stats with link.

### ISSUE THREAD

**Issue by kattni** [adafruit/adabot#136]
As we've added more boards, the list of downloads broken down by board has begun to become unwieldy in when included in the CircuitPython Weekly notes document. We've made changes in the past to the Libraries section of the library report to slim it down for the CP Weekly notes doc. I feel at this point, we should remove the actual tables from the library report. The information is available on https://circuitpython.org/stats (though the page is currently experiencing the same issues as the library report, and is therefore not displaying anything). I suggest we remove the tables from the library report and replace them with a link to the download stats on circuitpython.org. 

Instead we would include the total downloads of the current stable and current unstable releases, followed by a link to the breakdown on circuitpython.org.

@tannewt Thoughts?

**Comment by tannewt** [comment]
Fine with me!

**Comment by kattni** [comment]
@sommersoft Ok, include this with the other changes, please. Remove the download stats tables and instead include only the total downloads for stable and unstable, and a link to https://circuitpython.org/stats for further breakdowns. Thanks!
