### ISSUE TITLE
"CircuitPythonLibrarians team missing etc" check triggering incorrectly

### ISSUE THREAD

**Issue by kattni** [adafruit/adabot#146]
The list of results under the "CircuitPythonLibrarians team missing or does not have write access" check includes libraries for which this issue is not the case. It appears to be triggering on most libraries. Is it possible the way this check works has changed?

**Comment by sommersoft** [comment]
I can't see any reported changes, but the validator checks for the following which is no longer being returned in the results:

```
"permissions": {
    "admin": false,
    "push": false,
    "pull": true
  },
```

Will keep digging...

**Comment by sommersoft** [comment]
I submitted a question on this to the GitHub Forum: https://github.community/t5/GitHub-API-Development-and/API-v3-Get-Repo-Permissions/m-p/52000#M4453

Hopefully a "good" answer comes...

**Comment by kattni** [comment]
Thank you for following up on this.
