### ISSUE TITLE
Run on Travis

### ISSUE THREAD

**Issue by tannewt** [adafruit/adabot#16]
Move off the computer at my house onto Travis.

https://docs.travis-ci.com/user/cron-jobs/

**Comment by sommersoft** [comment]
Starting to research this, and the following infant idea popped in my head. This is just for documentation purposes (for now...I may pick this up).

In combination with #19, and having the option to output results to a file, we could also cron the weekly summary and upload to either:
- [GitHub Pages](https://docs.travis-ci.com/user/deployment/pages/) 
   - With `keep-history=True`
   - Travis-side secure token
   - I _think_ we can point the deployment to [adafruit-circuitpython-weekly-meeting](https://github.com/adafruit/adafruit-circuitpython-weekly-meeting) with either `local-dir` or `github-url`. This would use a Project Page (not User/Org). I'm unsure about being to use the current folder layout (`/2017/…`, `/2018/…`); looks like the Pages options are to use a branch, or `/docs/` on `master`.

- [GitHub Releases](https://docs.travis-ci.com/user/deployment/releases/) 
   - With secure OAuth Token (doesn't look like we can use Travis-side token)
   - Not sure it can be used to deploy to [adafruit-circuitpython-weekly-meeting](https://github.com/adafruit/adafruit-circuitpython-weekly-meeting). It mentions "GitHub Enterprise" on the Travis help page...not sure if it's synonymous though.
   - Doesn't "save" much work vs running locally with file output and uploading.

I guess we could also setup the cron job on the weekly-meeting repo, as opposed to here on adabot.

I imagine the weekly cron running Mondays to allow for any Sunday night push. Too bad you can't specify a time... 🙁 

**Addendum:**

In verifying/proof-reading the above, I came across this line on the Travis GitHub Pages help page:
```
Travis CI can deploy your static files to GitHub Pages after a successful build.
```
I initially interpreted this to mean that "non-static content", in this case new files, couldn't be uploaded. But, in discussion on Discord with @siddacious, I may be misinterpreting that. Will need further investigation and/or testing.

**Comment by tannewt** [comment]
How about S3 like the per-commit builds? I'd like it to run nightly too instead of weekly.

Thanks for your brain power on this!

**Comment by sommersoft** [comment]
adabot has a new friend: .travis.yml! 

https://travis-ci.com/sommersoft/adabot/builds/90151442

On my fork for testing; setup the Travis with the env variables that are currently in `env.sh`.

Adding the cron job now...we'll see if a new run shows up tomorrow or Sundy (its late).
