### ISSUE TITLE
Make commits since last release check ignore CI changes

### ISSUE THREAD

**Issue by kattni** [adafruit/adabot#161]
Changes made to the CI of a library have no effect on the code or the user, and therefore do not require a new release be made. We should update the checks to ignore changes made only to the CI so we can make those changes without requiring a library-wide release sweep every time. This would ensure we do not miss out on releasing code changes etc. when CI changes are applied across the board.

**Comment by sommersoft** [comment]
I've got the bare-bones of this working, looking only at dotfiles (`.github/`, `.pylintrc`, etc):

```
~/Dev/adabot/adabot:$> python3 -m adabot.circuitpython_libraries -v "validate_release_state" -e 100
Adafruit_CircuitPython_BLE_Magic_Light
        updated files['README.rst']
        non-CI/dot files: ['README.rst']
Adafruit_CircuitPython_Bitmap_Font
        updated files['adafruit_bitmap_font/bdf.py', 'docs/conf.py']
        non-CI/dot files: ['adafruit_bitmap_font/bdf.py', 'docs/conf.py']
Adafruit_CircuitPython_BLE_Radio
        updated files['.travis.yml', 'README.rst']
        non-CI/dot files: ['README.rst']
Adafruit_CircuitPython_CPython
        updated files['README.rst']
        non-CI/dot files: ['README.rst']
Adafruit_CircuitPython_LED_Animation
        updated files['README.rst']
        non-CI/dot files: ['README.rst']
Adafruit_CircuitPython_RPLIDAR
        updated files['README.rst']
        non-CI/dot files: ['README.rst']
Adafruit_CircuitPython_ProgressBar
        updated files['.readthedocs.yml']
        non-CI/dot files: []
Adafruit_CircuitPython_PyPortal
        updated files['README.rst', 'adafruit_pyportal.py']
        non-CI/dot files: ['README.rst', 'adafruit_pyportal.py']
Adafruit_CircuitPython_DS1841
        updated files['README.rst']
        non-CI/dot files: ['README.rst']
Adafruit_CircuitPython_Pypixelbuf
        updated files['.github/workflows/build.yml', '.pylintrc', 'CODE_OF_CONDUCT.md', 'README.rst', 'adafruit_pypixelbuf.py', 'docs/conf.py', 'docs/examples.rst', 'examples/pypixelbuf_simpletest.py', 'setup.py']
        non-CI/dot files: ['CODE_OF_CONDUCT.md', 'README.rst', 'adafruit_pypixelbuf.py', 'docs/conf.py', 'docs/examples.rst', 'examples/pypixelbuf_simpletest.py', 'setup.py']
```

Do we want anything more granular than that? Like `docs/conf.py`, `CODE_OF_CONDUCT.md`, etc?

**Comment by kattni** [comment]
I think more granular would be good. Any files that would not affect the user or the bundle could be included.

**Comment by sommersoft** [comment]
> I think more granular would be good. Any files that would not affect the user or the bundle could be included.

Okie dokie. I'll walk the file tree, and post up a list with thoughts/questions.

**Comment by sommersoft** [comment]
Here are my thoughts on ignore/don't ignore for each file [group]. `/docs/conf.py` is the only one I can't solidify an answer on...

- adafruit_*:
  - Never ignored. Period.
- dotfiles: 
  - `.github/*`, `.gitignore`, `.pylintrc`, `.readthedocs.yml`
  - Ignored. Only `.github/workflows/release.yml` and `.readthedocs.yml` would have any real impact on user-facing products. However, if someone is working on those, it should be known that a release is required and is also likely incremental work.

- CODE_OF_CONDUCT.md:
  - Ignored. `README.rst` on RTD links to the repo, and this file is not released or bundled.

- LICENSE:
  - Ignored. Only lives in the repo.

- README.rst:
  - Never ignored. Changes are user-facing on RTD, which requires a release to build.

- requirements.txt:
  - Never ignored. Changes could affect user-facing RTD (via .readthedocs.yml), and likely represent additions/changes to the library functionality.

- setup.py:
  - Never ignored. Release is required to trigger an update to PyPI.

- setup.py.disabled:
  - Ignored. Is only a placeholder to signify that a library is/will not be on PyPI.

- /examples/*:
  - Never ignored. Changes can affect user-facing RTD, and release/bundle assets.

- /docs/:
  - `_static/favicon.ico` & `*.rst`:
    - Never ignored. Changes affect user-facing RTD.
  - `conf.py`:
    - I want to say "ignored" for the same reasons as `release.yml` and `.readthedocs.yml` above. 
    - However, I could also see the same "never ignored" reasoning of `requirements.txt` above, when thinking about `autodoc_mock_imports` being updated.

**Comment by kattni** [comment]
@sommersoft Let's lean towards more careful and _not_ ignore `conf.py`. Everything else I agree with entirely.
