### ISSUE TITLE
Authentication w/ GitHub Search API Doesn't Persist

### ISSUE THREAD

**Issue by sommersoft** [adafruit/adabot#169]
While looking into differences with report results based on the person running the reports, I noticed that GitHub Search API authentication state isn't behaving as expected.

Specifically [here](https://github.com/adafruit/adabot/blob/b025932914f4d7338e2d871b9fc8bbcdc11e905c/adabot/lib/common_funcs.py#L195) and [here](https://github.com/adafruit/adabot/blob/b025932914f4d7338e2d871b9fc8bbcdc11e905c/adabot/arduino_libraries.py#L76).

The comment in the code says:
```
# Subsequent links have our access token already so we use requests directly.
```
However, I'm seeing that this isn't true based on inspecting the headers:
- First call to the search API with `github.get()`:
  - `X-RateLimit-Limit: 30` (authenticated rate limit per minute)

- Second call using the relational link and `requests.get()`:
  - `X-RateLimit-Limit: 10` (unauthenticated rate limit per minute)

Not sure if this is related to the change in using Basic Authentication with GitHub's auth changes, or changes in the requests library. It doesn't _seem_ to be causing any issues that I can verify right now, but will need some more research.

**Comment by siddacious** [comment]
👀
