### ISSUE TITLE
Update CircuitPython Library report to include markdown for use in CP Weekly notes

### ISSUE THREAD

**Issue by kattni** [adafruit/adabot#173]
Add the `### ` (three `#` and one space) before the section titles `Overview`, `Core`, `Libraries` and `Blinka` as it is copied into the notes document for the CircuitPython Weekly which is converted to markdown. Specifically the section titles begin [here](https://github.com/adafruit/adabot/blob/e5c9808e8f5a8ba40fa6f0b3794c25dc5372098c/adabot/circuitpython_libraries.py#L183).

**Comment by dherrada** [comment]
#174

**Comment by kattni** [comment]
Completed.
