### ISSUE TITLE
PyPI Download Stats for Blinka was None

### ISSUE THREAD

**Issue by makermelissa** [adafruit/adabot#180]
When I went to read the CircuitPython meeting notes, I noticed a line:
```
PyPI Downloads in the last week: None
```
This surprised me since I've not seen it under 1000. I also noticed that there appears to be missing stats at https://circuitpython.org/stats. I don't know if this is related to #162, but since this is new behavior since last week and that request has been open for months, it seems like something different.

**Comment by sommersoft** [comment]
It looks like `pypistats.org` is down. I just tried to visit it and it timed out, and the most recent report runs seem to reflect the same issue: https://github.com/adafruit/adabot/runs/969801164?check_suite_focus=true#step:10:23

#171 is a jumping off point to not rely on `pypistats.org`, but it wouldn't fix the meeting notes template report as it still relies on `pypistats.org`. It shouldn't be too difficult to fold in though.

**Comment by makermelissa** [comment]
Cool. Looks like it was working this week, so just a temporary glitch.
