### ISSUE TITLE
Add more libraries to Adafruit Blinka statistics

### ISSUE THREAD

**Issue by dhalbert** [adafruit/adabot#189]
The statistics for the Blinka "project" only include changes to the adafruit-blinka library. Add more blinka-related libraries to this set, including (I think).

- [ ] https://github.com/adafruit/Adafruit_Blinka_bleio
- [ ] https://github.com/adafruit/Adafruit_Blinka_Displayio
- [ ] https://github.com/adafruit/Adafruit_Python_PlatformDetect
- [ ] https://github.com/adafruit/Adafruit_Python_PureIO
- [ ] https://github.com/adafruit/Adafruit_Blinka_PyPortal
- [ ] https://github.com/adafruit/Adafruit_Python_Extended_Bus

@makermelissa Please edit this list, issue, or title as needed. Thanks.

**Comment by makermelissa** [comment]
I made mention of this back in December at https://github.com/adafruit/adabot/issues/119#issuecomment-571873848
