### ISSUE TITLE
Transition To GitHub API v4?

### ISSUE THREAD

**Issue by sommersoft** [adafruit/adabot#21]
Navigating to the API docs page, I came across the [API v4](https://developer.github.com/v4/) pages.

v4 seems to be dumping RESTful and moving to GraphQL. 

I've searched and tried to figure out when they _might_ sunset v3, and came up empty.

This is really just a placeholder issue...

**Comment by sommersoft** [comment]
There is still no announcement on any planned sunset of v3. However, I've been learning and playing around with v4 & GraphQL. It looks promising from the perspective of cutting down on both API requests and execution time.

**Comment by tekktrik** [comment]
Now resolved since it defaults to the latest API version: https://docs.github.com/en/rest/overview/api-versions?apiVersion=2022-11-28
