### ISSUE TITLE
Fix Mismatched .readthedocs.yml Validator

### ISSUE THREAD

**Issue by sommersoft** [adafruit/adabot#215]
https://github.com/adafruit/adabot/blob/61c7e4c17353d32f091e41d03ac5daff00414f66/adabot/lib/circuitpython_library_validators.py#L654-L661

Currently, all 269 libraries in the bundle are failing the above validator for `.readthedocs.yml`. This is due to the file SHA comparison, as they've all changed.

I did some analyzing, and there are now **9 different** SHAs across the ecosystem for `.readthedocs.yml` (listed below). Looking back through `validate_contents` history, I couldn't quite see a specific reason to check the SHA. I assume its just to combat version drift. Is that a correct assumption @tannewt, if you can recall?

The easy way to fix this is to just add the current SHAs to the conditonal (I already have this locally). But, at that level of variation, I'm wondering if this is even worthwhile anymore. Requesting comments/thoughts on this...

-------

`.readthedocs.yml` SHAs found:
```
f4243ad548bc5e4431f2d3c5d486f6c9c863888b
008347dfe421dd5aef1663fc700224e1a61a378b
a1e2575f7c34fbb6481088ca608c677bc079caa2
132b39d7b82b9a3aedf2ff2fb361b9645666e7f0
a9d14f7744acfcacc41bdb19ae4f61c4ca75d2cc
e9ea7a160a1b5db37840c3841b51e20b188f03c7
f63f6eedcb5f6b1b3c40d83613802e874e72afa7
011c3a97337b2b38700035d522c22b3bbad2cc73
ffa84c41736005ef37c99fb0a2af2a6aa47cd434
```  

Tagging: @kattni, @jepler, @dherrada

**Comment by dhalbert** [comment]
I agree - I don't see the point - what kind of version drift are we worried about, and in particular on this file?

**Comment by tannewt** [comment]
Shouldn't they all be the same? I'd expect them to be: https://github.com/adafruit/cookiecutter-adafruit-circuitpython/blob/master/%7B%25%20if%20cookiecutter.library_prefix%20%25%7D%7B%7B%20cookiecutter.library_prefix%20%7C%20capitalize%20%7D%7D_%7B%25%20endif%20%25%7DCircuitPython_%7B%7B%20cookiecutter.library_name%7D%7D/%7B%25%20if%20cookiecutter.sphinx_docs%20in%20%5B'y'%2C%20'yes'%5D%20%25%7D.readthedocs.yml%7B%25%20endif%20%25%7D

**Comment by sommersoft** [comment]
> Shouldn't they all be the same?

My guess is that the changes applied via patches, and the manual ones that patching doesn't work on, are where the unique SHAs came from. IIRC, the patches were for the license info.

**Comment by sommersoft** [comment]
A different approach to verifying this could be to use the cookiecutter's version as a reference, and then just use `pyyaml` to parse & compare?

**Comment by dherrada** [comment]
Yeah, I think just parsing them could be a better solution. That's what I've usually done when comparing them locally. That being said, not sure how much longer it'd take to run.

**Comment by sommersoft** [comment]
> That being said, not sure how much longer it'd take to run.

I mocked up a pyyaml contents comparison. No discernable change in runtime with `circuitpython_libraries.py` (allows me to isolate `validate_contents`). I might just go ahead and put it up as a PR and see what folks think...
