### ISSUE TITLE
Script For Library Download Stats [Bundle & PyPi]

### ISSUE THREAD

**Issue by dhalbert** [adafruit/adabot#22]
If you'd like download statistics for pypi:

https://pypistats.org/ and https://pypistats.org/api/
https://stackoverflow.com/questions/38102317/why-pypi-doesnt-show-download-stats-anymore (but see the newer answers)

Example: https://pypistats.org/packages/adafruit-blinka

Tagging @brennen @kattni @tannewt

**Comment by sommersoft** [comment]
Changed the issue title. In thinking about this, I think a separate script to get the download stats is better than just further expanding `circuitpython_libraries.py`. That script is _long_ as it is. As always, I can be overruled on that thought... :smile:

Also, we can get Bundle download stats. GitHub stats by library don't make sense, seeing that downloads from each repo is probably rare.

**Comment by tannewt** [comment]
Splitting it into a separate script sounds good to me!

**Comment by kattni** [comment]
Making another script is fine.
