### ISSUE TITLE
Some checks run very differently locally versus remotely

### ISSUE THREAD

**Issue by dherrada** [adafruit/adabot#229]
A number of checks, most notably the failing pylint check and the default branch check give wildly different results when run locally.

The pylint check brings up very few results locally but a bunch remotely. I'd guess it's different pylint versions.

Not sure about the default branch check, and it's not that relevant anymore, but I would still like to find out why it's different.

**Comment by sommersoft** [comment]
@dherrada can you give a example of how they're behaving differently?

I'd say the pylint differences would likely be version differences, as you said. With pylint not being pinned to a version, it would be easy to get out of sync on a local environment if `--force-reinstall` or the like isn't used.

**Comment by dherrada** [comment]
@sommersoft Yeah, that was it. Thanks!
