### ISSUE TITLE
release.yml is still on Python 3.6

### ISSUE THREAD

**Issue by lesamouraipourpre** [adafruit/adabot#234]
Just noticed that while `.github/workflows/build.yml` was updated to Python 3.7, `.github/workflows/release.yml` is still on Python 3.6
Should `release.yml` have been updated as well?

**Comment by sommersoft** [comment]
@lesamouraipourpre did you mean to file this on the [adafruit/cookiecutter-adafruit-circuitpython](https://github.com/adafruit/cookiecutter-adafruit-circuitpython/issues) repo instead?

_As a side note: I thought about this for the Actions workflows on this repo, as I was looking into `black`ifying adabot in prep for #225._

**Comment by lesamouraipourpre** [comment]
I wasn't sure where to file it. I know that a recent adabot patch pass updated Python to 3.7 in the build.yml.
If it makes more sense filing it on cookiecutter then could an admin move it over.

**Comment by tekktrik** [comment]
Resolved
