### ISSUE TITLE
Fix Actions to ignore checks requiring secrets

### ISSUE THREAD

**Issue by tekktrik** [adafruit/adabot#290]
Secrets don't get passed to pull requests, so currently the test CI will always fail.  Patching the tests to skip checks requiring secrets/tokens will make that workflow more flexible for contributions.

**Comment by makermelissa** [comment]
Would it be better to use actions to create a mock secrets.py file?

**Comment by tekktrik** [comment]
It's referencing the repository secrets that it needs for a few of the repo validation checks, which don't get passed to PRs.  I think monkeypatching to delete functions that need secrets should fix the issue.
