### ISSUE TITLE
Add Total Downloads To PyPi DL Stats

### ISSUE THREAD

**Issue by sommersoft** [adafruit/adabot#52]
Add total download stats from `pypistats.org`. Can be retrieved with the `/overall` API request.

This will also push a formatting change. Will tabulate results, like the Arduino script does.

**Comment by ladyada** [comment]
thanks! just an fyi - according to ben who helps run piwheels, these stats wont include piwheels downloads https://github.com/RPi-Distro/python-gpiozero/issues/702

**Comment by sommersoft** [comment]
Huh. I didn't even know piwheels was a thing, let alone a default for Stretch. I'll pin that and watch as the conversation develops. Thanks!

**Comment by sommersoft** [comment]
After some further reading, I'm going to park this here for future reference.

[piwheels GitHub: Issue #82 - Stats Page](https://github.com/bennuttall/piwheels/issues/82)

No API is mentioned, nor assumed (by me). Webpage is doable, since it can conceivably be scraped.

**Comment by kattni** [comment]
This has been added! If we choose to move forward with the piwheels stuff, we can create a new issue.

**Comment by bennuttall** [comment]
Sorry this is an old thread but in case it helps, the way to retrieve download stats for a package is documented in the "download stats" bit here: https://www.piwheels.org/json.html - so you can hit `packages.json` daily or at the end of the month or whatever for up-to-date numbers.

I've thrown something together here, hope it helps: https://github.com/adafruit/adabot/pull/205
