### ISSUE TITLE
Tabulate Core Download Stats

### ISSUE THREAD

**Issue by sommersoft** [adafruit/adabot#54]
With the translations, the core download stats have gotten long and eye-soreish. So, in an effort to reduce this, and make the meeting notes a little more mouse-wheel friendly, I figure tabulating the stats will do the trick.

```
Board        lang1   lang2   lang3
Feather        19      45     32
```

**Comment by kattni** [comment]
Sounds brilliant!

**Comment by sommersoft** [comment]
Soo...bit of an idea "fail". 😄 I scrolled passed the stats so much, I forgot that its not by board/language. Its release/board & release/language.

I still think I can squash it a little vertically.

**Comment by kattni** [comment]
It occurs to me that we could do like we do with the lib listings and maybe limit the stats to the top 10-20 boards or something.

This may mean that no community boards would end up on the list. My thought there is perhaps we add a file to the core repo, circuitpython_stats.md or something, that has a nicely rendered table of all the download statistics, and then show the top whatever in the weekly notes, and link to that file so people can see the rest if they'd like.

**Comment by sommersoft** [comment]
Thoughts?
```
Download stats by board:

| Board                                | 3.1.2  | 4.0.0-beta.0  |
| -------------------------------------|--------|---------------|
| arduino_mkr1300                      |   -    |       0       |
| arduino_mkrzero                      |   -    |       0       |
| arduino_zero                         |  115   |       0       |
| catwan_usbstick                      |   -    |       0       |
| circuitplayground_express            |  618   |       1       |
| circuitplayground_express_crickit    |  122   |       1       |
| feather52832                         |   23   |       -       |
| feather_huzzah                       |  221   |       -       |
| feather_m0_adalogger                 |   52   |       1       |
| feather_m0_basic                     |   84   |       1       |
| feather_m0_express                   |  131   |       1       |
| feather_m0_express_crickit           |   15   |       1       |
| feather_m0_rfm69                     |   15   |       1       |
| feather_m0_rfm9x                     |   22   |       1       |
| feather_m4_express                   |  163   |       2       |
| feather_nrf52840_express             |   -    |       1       |
| feather_radiofruit_zigbee            |   -    |       0       |
| gemma_m0                             |   69   |       1       |
| grandcentral_m4_express              |   -    |       1       |
| hallowing_m0_express                 |   48   |       1       |
| itsybitsy_m0_express                 |   77   |       1       |
| itsybitsy_m4_express                 |   97   |       2       |
| makerdiary_nrf52840_mdk              |   -    |       0       |
| makerdiary_nrf52840_mdk_usb_dongle   |   -    |       0       |
| meowmeow                             |   -    |       0       |
| metro_m0_express                     |   99   |       0       |
| metro_m4_express                     |   71   |       6       |
| mini_sam_m4                          |   -    |       0       |
| particle_argon                       |   -    |       2       |
| particle_boron                       |   -    |       0       |
| particle_xenon                       |   -    |       0       |
| pca10056                             |   -    |       0       |
| pca10059                             |   -    |       0       |
| pirkey_m0                            |   7    |       0       |
| pyportal                             |   -    |       0       |
| sparkfun_nrf52840_mini               |   -    |       0       |
| sparkfun_samd21_mini                 |   -    |       0       |
| trellis_m4_express                   |   -    |       3       |
| trinket_m0                           |  311   |       1       |
| -------------------------------------|--------|---------------|
|                                Total |  2360  |      29       |
| -------------------------------------|--------|---------------|

```

Haven't done languages yet, but will be the same...

**Comment by siddacious** [comment]
verra-naas

**Comment by kattni** [comment]
Even like this, it looks much cleaner. I also like the easy comparison of the two versions.

It occurs to me that "top x boards" would have to choose between stable or unstable, and sort by that, or you'd need more tables. So in the end you wouldn't save as many lines because the top downloads may not match between stable and unstable. So we would have to separate stable and unstable into two separate tables, of say, 10 each, which would still save more space, but not as much as if they were the same. 

So only showing the top 10 boards may still be worth considering, but I think it would require separate tables for stable and unstable. But it does have the downside of no longer highlighting the rest of the boards. 

I think the iteration you pasted above is a good start, @sommersoft. I would suggest doing it. We can continue to refine it if we decide we want to do that.
