### ISSUE TITLE
Have Adabot Update CPy Libraries Issue Text on Core Repo

### ISSUE THREAD

**Issue by sommersoft** [adafruit/adabot#77]
In relation to #76, have adabot update the [CircuitPython Libraries!](https://github.com/adafruit/circuitpython/issues/1246) issue on the core repo, using the GitHub API.

Currently, the website is not allowing updates to the body of the issue. GitHub support has not responded with a fix.

**Comment by kattni** [comment]
I think we're going to abandon the idea of updating that issue. We instead will find a static place to host the content, and link to the static location from the issue body. 

At the moment, my intention is to host it on circuitpython.org. We can discuss this further. I will be filing an issue on the circuitpython-org repo with a mock up of what I'm envisioning and see whether we can get it going.
