### ISSUE TITLE
Update text in AutoRelease

### ISSUE THREAD

**Issue by makermelissa** [adafruit/adabot#95]
Currently the text comes as:
```
The libraries in each release are compiled for all recent major versions of CircuitPython. Please download the one that matches the major version of your CircuitPython. For example, if you are running 3.0.0 you should download the 3.x bundle.

To install, simply download the matching zip file, unzip it, and copy the lib folder onto your CIRCUITPY drive. Non-express boards such as the Trinket M0, Gemma M0 and Feather M0 Basic will need to selectively copy files over.
```
However, with the bundle getting larger, copying over the entire lib folder to the CIRCUITPY drive isn't so feasible anymore. 

Also, maybe update the example to be 4.0.0 and 4.x bundle since that is current.

**Comment by ladyada** [comment]
agreed - @makermelissa @sommersoft  either of you want to update the text as a PR? i can review it

**Comment by makermelissa** [comment]
Sure, I can take a stab at it.
